### ISSUE TITLE
出现问题了。求看求看

### ISSUE THREAD

**Issue by zonda11** [Jimmey-Jiang/Common.Utility#13]
这个不存在与上下文中，编译不通过，而且配置文件类中又出现了相同类型的GetConfigString()方法名，我感觉应该是重复了，后来我注释了，然后又有问题了错误，	缺少编译器要求的成员“System.Runtime.CompilerServices.ExtensionAttribute..ctor”，然后那个帮助文档打开了看不了，没联网。能解决下吗大哥，

**Comment by qljiong** [comment]
@zonda11 注释掉重复的方法就可以编译了。你再看看代码。排除一下问题就行了。
