### ISSUE TITLE
没必要每个源码文件都加这个广告吧

### ISSUE THREAD

**Issue by Yahasana** [Jimmey-Jiang/Common.Utility#3]
https://github.com/Jimmey-Jiang/Common.Utility/blob/a5c17d339023a3b6fc26b7f9b70030d130413d6f/Utility%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%A4%A7%E5%85%A8/PDFHelper.cs#L2

**Comment by Jimmey-Jiang** [comment]
谢谢提醒，已改过来
