### ISSUE TITLE
汉字转拼音首字母大写方法存在BUG

### ISSUE THREAD

**Issue by Dygood** [Jimmey-Jiang/Common.Utility#4]
如题,该方法存在BUG,因为在实际项目中遇到过,后已经修复.
错误:
                    else if (key >= '\uCEF4' && key <= '\uD188')
                    {
                        strResult = strResult + "X";
                    }
修正方式:
                    else if (key >= '\uCEF4' && key <= '\uD1B8')
                    {
                        strResult = strResult + "X";
                    }
会导致部分X开头的汉字转换失败,如: '血'.
同时还有更高效的转码方式:
源码链接如下:
https://github.com/Dygood/XPinYin

**Comment by Jimmey-Jiang** [comment]
谢谢，根据您的意见已经修复
